name = "MC ASI Online"
author = "Poligorn"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36353b5f8f21ef68df8b03e145702de1a6f50bca0260b2b8b2fae8df2a79ed43"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
