name = "MC ASI Online"
author = "Poligorn"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0448d045020d1780f0da164e4a721c64787fcffcc3496dd24728a1608f252b00"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
