name = "MC ASI Online"
author = "Poligorn"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32401d7c5978c23441158b47c9912b9d81ef95fa943e5ee4814bf01c1d12e1b9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
