#Enables additional server-side Custom Claims debug logging.
debug_logging = false
#Operator level accepted by the permission service.
# Default: 2
# Range: 0 ~ 4
op_permission_level = 2

[permissions]
	#Permission nodes granted to every player without requiring OP or tags.
	default_player_permissions = ["customclaims.war.start", "customclaims.war.status", "customclaims.explosions.status", "customclaims.explosions.toggle", "customclaims.create.status", "customclaims.create.toggle", "customclaims.assembly.status", "customclaims.assembly.toggle"]
